[credentials]
api_url = https://www.vpinleaders.com
machine_id = 
api_key = 

[screenshot]
enable = true
capture_screen = 0

[score-mode]
scores = true
challenge = false

[send-mode]
send_mode = automatic

[hotkeys]
keyboard = cmd+shift+s
joystick_buttons = 

[notification-sound]
; Batocera only
enabled = true
language = pt

[nvram]
base_dir = /path/to/your/nvram-base-dir

[logging]
file = ~/.vpinleaders/logs/vpinleaders.log

[challenge]
challenge_id = 
